/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fts_gl_GLNativeInterface */

#ifndef _Included_fts_gl_GLNativeInterface
#define _Included_fts_gl_GLNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    uiInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_uiInit
  (JNIEnv *, jclass);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    frameStart
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_frameStart
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    frameEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_frameEnd
  (JNIEnv *, jclass);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    setColor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_setColor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawRect
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawRect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawFilledRect
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawFilledRect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    getTextSize
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_fts_gl_GLNativeInterface_getTextSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    createFont
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fts_gl_GLNativeInterface_createFont
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    setFontSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_setFontSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    setFontName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_setFontName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
