/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fts_gl_GLNativeInterface */

#ifndef _Included_fts_gl_GLNativeInterface
#define _Included_fts_gl_GLNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    uiInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_uiInit
  (JNIEnv *, jclass);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    frameStart
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_frameStart
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    frameEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_frameEnd
  (JNIEnv *, jclass);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawRect
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
