/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fts_gl_GLNativeInterface */

#ifndef _Included_fts_gl_GLNativeInterface
#define _Included_fts_gl_GLNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    uiInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_uiInit
  (JNIEnv *, jclass);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    frameStart
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_frameStart
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    frameEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_frameEnd
  (JNIEnv *, jclass);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    viewStart
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_viewStart
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    viewEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_viewEnd
  (JNIEnv *, jclass);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    setColor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_setColor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawText
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawText
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawRect
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawRect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawFilledRect
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawFilledRect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawGraidentRect
 * Signature: (IIIIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawGraidentRect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawLine
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawLine
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    getTextSize
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_fts_gl_GLNativeInterface_getTextSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    createBackBuffer
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fts_gl_GLNativeInterface_createBackBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    destroyBackBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_destroyBackBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    bindBackBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_bindBackBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    unbindBackBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_unbindBackBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drawBackBuffer
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawBackBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    createFont
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fts_gl_GLNativeInterface_createFont
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    setFontSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_setFontSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    setFontName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_setFontName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    createImage
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_fts_gl_GLNativeInterface_createImage
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    getImageSize
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_fts_gl_GLNativeInterface_getImageSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    destroyImage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_destroyImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     fts_gl_GLNativeInterface
 * Method:    drwawImage
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_fts_gl_GLNativeInterface_drawImage
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
