/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fts_demo_gl_LinuxNativeInterface */

#ifndef _Included_fts_demo_gl_LinuxNativeInterface
#define _Included_fts_demo_gl_LinuxNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fts_demo_gl_LinuxNativeInterface
 * Method:    windowOpen
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fts_demo_gl_LinuxNativeInterface_windowOpen
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     fts_demo_gl_LinuxNativeInterface
 * Method:    windowSwapBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_demo_gl_LinuxNativeInterface_windowSwapBuffers
  (JNIEnv *, jclass);

/*
 * Class:     fts_demo_gl_LinuxNativeInterface
 * Method:    windowClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fts_demo_gl_LinuxNativeInterface_windowClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
